name: SpigotFunPlugin
main: io.github.codecube.spigotfun.SpigotFunPlugin
version: 1.0
commands: 
  funtest:
    description: It does fun things to test stuff!
    usage: /funtest [anything] [but] [these] [args] [will] [not] [make] [a] [difference]
  buildobject:
    description: Opens an object editor to build new objects with.
    usage: /buildobject
  save:
    description: Saves an object that you are editing.
    usage: /save [object name]