name: Waterfall
main: io.github.codecube.waterfall.core.WaterfallPlugin
version: 1.0
commands: 
  funtest:
    description: It does fun things to test stuff!
    usage: /funtest [anything] [but] [these] [args] [will] [not] [make] [a] [difference]
  editor:
    description: Opens the editor, or closes it if you are already using it.
    usage: /editor
  save:
    description: Saves an object that you are editing.
    usage: /save [object name]